### ISSUE TITLE
Android - 7.5.0.GA - Errors

### ISSUE THREAD

**Issue by antonioduran** [appcelerator-modules/ti.flurry#40]
01-05 11:16:28.117 32694-32694/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.app.cctest, PID: 32694
java.lang.NoSuchMethodError: No super method c()Ljava/util/Set; in class Lcom/flurry/sdk/ma; or its super classes (declaration of 'com.flurry.sdk.ma' appears in /data/app/com.app.cctest-be622iHp2nKhZBw20d_D4g==/base.apk:classes2.dex)
at com.flurry.sdk.ma$a.uncaughtException(SourceFile:1083)
at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1225)
at org.appcelerator.titanium.proxy.ActivityProxy.handleMessage(ActivityProxy.java:394)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:166)
at android.app.ActivityThread.main(ActivityThread.java:7425)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

----
[WARN]  libEGL: EGLNativeWindowType 0x7abe50e010 disconnect failed
[WARN]  FlurryAgent: Flurry session paused for context:org.appcelerator.titanium.TiActivity@ef76a64
[INFO]  zygote64: Deoptimizing void org.appcelerator.titanium.view.TiUIView.release() due to JIT inline cache
[WARN]  FlurryAgent: Flurry session ended
[WARN]  W/System.err: java.lang.InternalError: Thread starting during runtime shutdown
[WARN]  W/System.err: 	at java.lang.Thread.nativeCreate(Native Method)
[WARN]  W/System.err: 	at java.lang.Thread.start(Thread.java:753)
[WARN]  W/System.err: 	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
[WARN]  W/System.err: 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1386)
[WARN]  W/System.err: 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
[WARN]  W/System.err: 	at com.flurry.sdk.ke.a(SourceFile:142)
[WARN]  W/System.err: 	at com.flurry.sdk.ix.a(SourceFile:160)
[WARN]  W/System.err: 	at com.flurry.sdk.kr.g(SourceFile:268)
[WARN]  W/System.err: 	at com.flurry.sdk.kr$4.a(SourceFile:128)
[WARN]  W/System.err: 	at com.flurry.sdk.lw.run(SourceFile:49)
[WARN]  W/System.err: 	at android.os.Handler.handleCallback(Handler.java:808)
[WARN]  W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:101)
[WARN]  W/System.err: 	at android.os.Looper.loop(Looper.java:166)
[WARN]  W/System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by hansemannn** [comment]
@garymathews May this be a 7.5.0 regression?

**Comment by antonioduran** [comment]
Hello @hansemannn . I created also a jira ticket - https://jira.appcelerator.org/browse/MOD-2488
